library my_prj.globals;
import 'dart:io';

import 'package:myapp/src/models/MessageResource.dart';
bool isSup = false;
bool isRider = false;
bool isAdmin = false;
String token;
String onlyToken;
String Path_ImageProfile;
String txtSumPending;
String Path_Imageheader;
String Fname;
String Lname;
String s_EMP_NO;
String s_User_ID;
String user_Path;
String employeeType;
String s_EMP_TYPE;
String sPhoneNo;
String i_EMP_ID;
String companyId;
List listStores = List();
List<Msg> listMessage = new List<Msg>();